# Generated by Django 5.2.5 on 2025-09-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('outlet_id', models.AutoField(primary_key=True, serialize=False)),
                ('outlet_name', models.CharField(max_length=200)),
                ('pic_sm', models.CharField(blank=True, help_text='Person in charge (SM)', max_length=100, null=True)),
                ('sm_number', models.CharField(blank=True, help_text='SM phone number', max_length=30, null=True)),
                ('total_sva', models.IntegerField(default=0, help_text='Total Service Advisors')),
                ('avg_intake_service', models.IntegerField(default=0)),
                ('num_machines', models.IntegerField(default=0, help_text='Number of machines at this outlet')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['outlet_name'],
            },
        ),
    ]
