# Generated by Django 5.2.5 on 2025-09-23 14:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0002_outlet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('firmware_version', models.CharField(blank=True, max_length=50, null=True)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('installed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('device', models.OneToOneField(blank=True, help_text='Only one device (ESP32) can be bound at a time', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine', to='telemetry.device')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='telemetry.outlet')),
            ],
        ),
    ]
