# Generated by Django 5.2.5 on 2025-09-23 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0003_device_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='outlet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='telemetry.outlet'),
        ),
    ]
