# Generated by Django 5.2.5 on 2025-09-24 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0004_alter_machine_outlet'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('wifi_connected', models.BooleanField(default=False)),
                ('rtc_available', models.BooleanField(default=False)),
                ('sd_card_available', models.BooleanField(default=False)),
                ('current_count_basic', models.IntegerField(default=0)),
                ('current_count_standard', models.IntegerField(default=0)),
                ('current_count_premium', models.IntegerField(default=0)),
                ('uptime_seconds', models.IntegerField(default=0)),
                ('device_timestamp', models.CharField(blank=True, max_length=50, null=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='TelemetryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('event_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('event', models.CharField(default='treatment', max_length=50)),
                ('treatment', models.CharField(blank=True, max_length=20, null=True)),
                ('counter', models.IntegerField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('BASIC', 'Basic Treatment'), ('STANDARD', 'Standard Treatment'), ('PREMIUM', 'Premium Treatment'), ('status', 'Status Update')], default='status', max_length=20)),
                ('count_basic', models.IntegerField(blank=True, null=True)),
                ('count_standard', models.IntegerField(blank=True, null=True)),
                ('count_premium', models.IntegerField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('device_timestamp', models.CharField(blank=True, max_length=50, null=True)),
                ('wifi_status', models.BooleanField(default=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['-last_seen', 'device_id']},
        ),
        migrations.RemoveField(
            model_name='device',
            name='firmware_version',
        ),
        migrations.RemoveField(
            model_name='device',
            name='last_heartbeat',
        ),
        migrations.AddField(
            model_name='device',
            name='assigned',
            field=models.BooleanField(default=False, help_text='Whether device is assigned to a machine'),
        ),
        migrations.AddField(
            model_name='device',
            name='firmware',
            field=models.CharField(blank=True, help_text='Firmware version', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(blank=True, help_text='Last time device was seen online', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='mac',
            field=models.CharField(default='00:00:00:00:00:00', help_text='MAC address of the ESP32 device', max_length=17, unique=True),
        ),
        migrations.AddField(
            model_name='device',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the device', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='token',
            field=models.CharField(blank=True, help_text='Authentication token', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(help_text='Unique device identifier', max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='UsageStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('basic_count', models.IntegerField(default=0)),
                ('standard_count', models.IntegerField(default=0)),
                ('premium_count', models.IntegerField(default=0)),
                ('total_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outlet_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telemetry.outlet')),
            ],
            options={
                'ordering': ['-date', 'device_id'],
                'unique_together': {('device_id', 'date')},
            },
        ),
    ]
