# Generated by Django 5.2.5 on 2025-09-24 01:01

from django.db import migrations


def update_device_ids_to_mac(apps, schema_editor):
    """Update all existing devices to use MAC address as device_id"""
    Device = apps.get_model('telemetry', 'Device')
    DeviceStatus = apps.get_model('telemetry', 'DeviceStatus')
    TelemetryEvent = apps.get_model('telemetry', 'TelemetryEvent')
    
    for device in Device.objects.all():
        old_device_id = device.device_id
        new_device_id = device.mac
        
        if old_device_id != new_device_id:
            # Update DeviceStatus records
            DeviceStatus.objects.filter(device_id=old_device_id).update(device_id=new_device_id)
            
            # Update TelemetryEvent records
            TelemetryEvent.objects.filter(device_id=old_device_id).update(device_id=new_device_id)
            
            # Update Device record
            device.device_id = new_device_id
            device.save()


def reverse_update_device_ids(apps, schema_editor):
    """Reverse migration - not implemented as it would lose data"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0005_devicestatus_telemetryevent_alter_device_options_and_more'),
    ]

    operations = [
        migrations.RunPython(update_device_ids_to_mac, reverse_update_device_ids),
    ]
