from django.db import migrations, models
import random


REGIONS = [
    "CENTRAL 1",
    "CENTRAL 2",
    "NORTHERN",
    "SOURTHERN",
    "EAST COAST",
    "EAST M'SIA",
    "INDONESIA",
]


def assign_random_regions(apps, schema_editor):
    Outlet = apps.get_model('telemetry', 'Outlet')
    for outlet in Outlet.objects.all():
        if not getattr(outlet, 'region', None):
            outlet.region = random.choice(REGIONS)
            outlet.save(update_fields=["region"])


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0004_alter_machine_outlet'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='region',
            field=models.CharField(max_length=32, blank=True, null=True, help_text='Geographical region for reporting'),
        ),
        migrations.RunPython(assign_random_regions, migrations.RunPython.noop),
    ]

# Generated by Django 5.2.5 on 2025-09-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0006_auto_20250924_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='region',
            field=models.CharField(blank=True, help_text='Geographical region for reporting', max_length=32, null=True),
        ),
    ]
