# Generated by Django 5.2.5 on 2025-09-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0006_migrate_machine_devices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(db_index=True, max_length=32, unique=True)),
                ('device_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('token', models.CharField(max_length=128, unique=True)),
                ('assigned', models.BooleanField(default=False)),
                ('firmware', models.CharField(blank=True, max_length=50, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-last_seen', 'device_id'],
            },
        ),
        migrations.AddField(
            model_name='telemetryevent',
            name='counter',
            field=models.IntegerField(blank=True, help_text='Counter value at press time', null=True),
        ),
        migrations.AddField(
            model_name='telemetryevent',
            name='event',
            field=models.CharField(blank=True, help_text="e.g., 'treatment'", max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='telemetryevent',
            name='event_id',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='telemetryevent',
            name='treatment',
            field=models.CharField(blank=True, help_text='BASIC|STANDARD|PREMIUM', max_length=16, null=True),
        ),
    ]
