# Generated by Django 5.2.5 on 2025-09-19 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0008_alter_machine_options_alter_machine_outlet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['outlet__name', 'name']},
        ),
        migrations.AlterField(
            model_name='machine',
            name='outlet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='telemetry.outlet'),
        ),
    ]
