# Generated by Django 5.2.5 on 2025-09-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0008_alter_machine_machine_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='id',
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
