# Generated by Django 5.2.5 on 2025-09-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0009_alter_machine_options_alter_machine_outlet'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='average_intage_services',
            field=models.IntegerField(blank=True, help_text='Average intage services', null=True),
        ),
        migrations.AddField(
            model_name='outlet',
            name='number_of_machines',
            field=models.IntegerField(blank=True, help_text='Number of machines at outlet', null=True),
        ),
        migrations.AddField(
            model_name='outlet',
            name='total_sva',
            field=models.IntegerField(blank=True, help_text='Total Service Advisors', null=True),
        ),
    ]
