# Generated by Django 5.2.5 on 2025-09-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0009_remove_machine_id_alter_machine_machine_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='machine_id',
        ),
        migrations.AddField(
            model_name='machine',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
