# Generated by Django 5.2.5 on 2025-09-24 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0010_remove_machine_machine_id_machine_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='name',
            new_name='machine_code',
        ),
    ]
