# Generated by Django 5.2.5 on 2025-09-19 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0010_outlet_average_intage_services_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelemetryRecord',
        ),
    ]
