# Generated by Django 5.2.5 on 2025-09-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0011_rename_name_machine_machine_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='id',
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
