# Generated by Django 5.2.5 on 2025-09-25 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0012_remove_machine_id_machine_machine_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_id', models.CharField(help_text='Unique command identifier', max_length=100, unique=True)),
                ('command_type', models.CharField(choices=[('RESET_COUNTERS', 'Reset Counters'), ('CLEAR_MEMORY', 'Clear Memory'), ('CLEAR_QUEUE', 'Clear Queue'), ('REBOOT_DEVICE', 'Reboot Device'), ('UPDATE_SETTINGS', 'Update Settings'), ('GET_STATUS', 'Get Status'), ('SYNC_TIME', 'Sync Time'), ('UPDATE_FIRMWARE', 'Update Firmware')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=10)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Command parameters/data')),
                ('description', models.TextField(blank=True, help_text='Human-readable description')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('executed', 'Executed'), ('failed', 'Failed'), ('timeout', 'Timeout')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, default=dict, help_text='ESP32 response data')),
                ('error_message', models.TextField(blank=True, help_text='Error message if failed')),
                ('retry_count', models.IntegerField(default=0, help_text='Number of retry attempts')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Command expiration time', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='telemetry.device')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device', 'status'], name='telemetry_c_device__326cc0_idx'), models.Index(fields=['status', 'priority'], name='telemetry_c_status_7b47e1_idx'), models.Index(fields=['created_at'], name='telemetry_c_created_49b144_idx')],
            },
        ),
    ]
