# Generated by Django 5.2.5 on 2025-09-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0013_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicestatus',
            name='last_poll',
            field=models.DateTimeField(blank=True, help_text='Last time ESP32 polled for commands', null=True),
        ),
    ]
